# TODO: Delete this file for open source
name: AI PR Reviewer
on:
  pull_request:
    branches:
      - master
    types: [labeled, opened, synchronize, ready_for_review]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  raid:
    name: RAID
    uses: consumer/bedrock-pr-reviewer/.github/workflows/raid.yml@master
    with:
      code-convention-rollout-percentage: 100
      review-rollout-percentage: 100
